---

db_host: postgis-test
redis_cache: redis-test

services:
  - name: postgis-test
    templates: ../k8s/database/
    pvc_name: db-test
    sub_path: database-test
    databases:
      - zrc-test
      - drc-test
      - ztc-test
      - brc-test
      - nrc-test
      - ac-test
      - token-issuer-test
      - kic-test

  - name: redis-test
    templates: ../k8s/cache/

  - name: ac-test
    templates: ../k8s/ac/
    image_tag: develop

  - name: brc-test
    templates: ../k8s/brc/
    image_tag: develop

  - name: drc-test
    templates: ../k8s/drc/
    image_tag: develop
    min_upload_size: 4294967296  # 4GB

  - name: nrc-test
    templates: ../k8s/nrc/
    image_tag: develop

  - name: zrc-test
    templates: ../k8s/zrc/
    image_tag: develop

  - name: ztc-test
    templates: ../k8s/ztc/
    image_tag: develop

  - name: docs-test
    templates: ../k8s/docs

  - name: token-issuer-test
    templates: ../k8s/tokens

  - name: kic-test
    templates: ../k8s/kic/
    image_tag: 'latest'

ingress:
  name: ref-implementatie-test
  instance: test
  services:
    - host: zaken-api.test.vng.cloud
      name: zrc-test
    - host: documenten-api.test.vng.cloud
      name: drc-test
    - host: catalogi-api.test.vng.cloud
      name: ztc-test
    - host: autorisaties-api.test.vng.cloud
      name: ac-test
    - host: besluiten-api.test.vng.cloud
      name: brc-test
    - host: notificaties-api.test.vng.cloud
      name: nrc-test
    - host: zaken-auth.test.vng.cloud
      name: token-issuer-test
    - host: klantinteracties-api.test.vng.cloud
      name: kic-test
