---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: vrl
  namespace: zgw
  labels:
    k8s-app: vrl
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: vrl
  template:
    metadata:
      name: vrl
      labels:
        k8s-app: vrl
    spec:
      containers:
      - name: vrl
        image: vngr/vng-referentielijsten:0.5.2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "5m"
          limits:
            memory: "350Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /api/v1/
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 5
          periodSeconds: 5

        env:
          - name: DJANGO_SETTINGS_MODULE
            value: vrl.conf.docker
          - name: DB_HOST
            value: postgis
          - name: DB_NAME
            value: vrl
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: vrl-secrets
                key: SECRET_KEY
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vrl-secrets
                key: DB_PASSWORD
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: vrl-secrets
                key: SENTRY_DSN

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: vrl
  namespace: zgw
  labels:
    k8s-app: vrl
spec:
  selector:
    k8s-app: vrl
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
