---

# This playbook is executed locally and requires the kubectl binary

- name: Deploy the stable environment in the k8s cluster
  hosts: local

  vars_files:
    - vars/secrets.yml
    - vars/stable.yml

  tasks:
    - name: Install secrets
      k8s:
        state: present
        namespace: zgw
        definition: "{{ lookup('template', item) }}"
        validate:
          fail_on_error: yes
      with_items:
        - ../k8s/tokens/secrets.yml
        - ../k8s/vrl/secrets.yml
        - ../k8s/deploy/secrets.yml
        - ../k8s/inway/secrets.yml

    - include_tasks: tasks/deploy_service.yml
      loop: "{{ services }}"
      loop_control:
        loop_var: service
