---

# This playbook is executed locally and requires the kubectl binary

- name: Deploy the secrets in the k8s cluster
  hosts: local

  vars_files:
    - vars.yml

  tasks:
    - name: Install secrets
      k8s:
        state: present
        namespace: zgw
        definition: "{{ lookup('template', item) }}"
        validate:
          fail_on_error: yes
      with_items:
        - ../k8s/database/secrets.yml
        - ../k8s/zrc/secrets.yml
        - ../k8s/drc/secrets.yml
        - ../k8s/ztc/secrets.yml
        - ../k8s/brc/secrets.yml
        - ../k8s/nrc/secrets.yml
        - ../k8s/ac/secrets.yml
        - ../k8s/tokens/secrets.yml
        - ../k8s/vrl/secrets.yml
        - ../k8s/deploy/secrets.yml
        - ../k8s/inway/secrets.yml
